---
title: "HemOnc Concept Class Graph"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HemOnc Concept Class Graph}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(chariot2)
library(tidyverse)
```

This package creates a properly formatted output from the OMOP 
Vocabularies for consumption by the DiagrammeR package.  

```{r}
# Fetch from Postgres  
nodes_and_edges <-
  ne_fetch_concept_classes(conn_fun = "pg13::local_connect()")
```

```{r}
# Customize Nodes Attributes  
nodes_and_edges <-
  map_node_attributes(nodes_and_edges)
```

```{r}
# Customize Edge Attributes
nodes_and_edges <-
  map_edge_attributes(nodes_and_edges)
```

```{r}
# Construct Final Graph
final_graph <-
  construct_graph(nodes_and_edges)
final_graph$graph
```


```{r}
library(DiagrammeR)
```

```{r}
final_graph$graph %>%
  select_nodes(type == "Component") %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(type == "Component") %>%
  trav_out() %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(type == "Component") %>%
  trav_in() %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(type == "Component") %>%
  trav_out_edge() %>%
  trav_out_node(type == "Ingredient")%>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  trav_out_edge() %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  trav_out_edge() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  trav_out_edge(rel == "Subsumes") %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  trav_both_edge(is_hierarchical == 0) %>%
  get_edge_attrs("rel")
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  # select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out_until(max_steps = 2) %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```
