---
title: "Rescale Graph"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rescale Graph}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(chariot2)
library(tidyverse)
```

```{r,results='hide'}
# Fetch from Postgres  
nodes_and_edges <-
  ne_fetch_concept_classes(conn_fun = "pg13::local_connect()")

# Customize Nodes Attributes  
nodes_and_edges <-
  map_node_attributes(nodes_and_edges)

# Customize Edge Attributes
nodes_and_edges <-
  map_edge_attributes(nodes_and_edges)

# Construct Final Graph
final_graph <-
  construct_graph(nodes_and_edges)
final_graph$graph
```


```{r}
library(DiagrammeR)
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  set_node_attrs_ws(node_attr = "fontsize", value = 26) %>%
  set_edge_attrs(edge_attr = "fontsize", value = 26) %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```


```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  set_node_attrs_ws(node_attr = "fontsize", value = 26) %>%
  set_node_attrs_ws(node_attr = "width", value = 4) %>%
  set_node_attrs_ws(node_attr = "height", value = 4) %>%
  set_edge_attrs(edge_attr = "fontsize", value = 26) %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```


```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  set_node_attrs_ws(node_attr = "fontsize", value = 26) %>%
  set_node_attrs_ws(node_attr = "width", value = 4) %>%
  set_node_attrs_ws(node_attr = "height", value = 4) %>%
  set_edge_attrs(edge_attr = "fontsize", value = 26) %>%
  set_edge_attrs(edge_attr = "len", value = 35) %>%
  transform_to_subgraph_ws() %>%
  render_graph()
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  set_node_attrs_ws(node_attr = "fontsize", value = 4) %>%
  set_node_attrs_ws(node_attr = "width", value = .5) %>%
  set_node_attrs_ws(node_attr = "height", value = .5) %>%
  set_edge_attrs(edge_attr = "fontsize", value = 4) %>%
  set_edge_attrs(edge_attr = "len", value = .4) %>%
  transform_to_subgraph_ws() %>%
  render_graph("circle")
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  set_node_attrs_ws(node_attr = "fontsize", value = 3) %>%
  set_node_attrs_ws(node_attr = "width", value = .4) %>%
  set_node_attrs_ws(node_attr = "height", value = .4) %>%
  set_edge_attrs(edge_attr = "fontsize", value = 3) %>%
  set_edge_attrs(edge_attr = "len", value = 6) %>%
  transform_to_subgraph_ws() %>%
  render_graph("kk")
```

```{r}
final_graph$graph %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  select_nodes(type == "Regimen Class", set_op = "intersect") %>%
  trav_out() %>%
  select_nodes(vocabulary_id == "HemOnc") %>%
  set_node_attrs_ws(node_attr = "fontsize", value = 3) %>%
  set_node_attrs_ws(node_attr = "width", value = .4) %>%
  set_node_attrs_ws(node_attr = "height", value = .4) %>%
  set_edge_attrs(edge_attr = "fontsize", value = 3) %>%
  set_edge_attrs(edge_attr = "len", value = 6) %>%
  transform_to_subgraph_ws() %>%
  render_graph("fr")
```
